
[functions.guestbook-create]
enabled = true
verify_jwt = true
import_map = "./functions/guestbook-create/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/guestbook-create/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/guestbook-create/*.html" ]

[functions.guestbook-delete]
enabled = true
verify_jwt = true
import_map = "./functions/guestbook-delete/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/guestbook-delete/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/guestbook-delete/*.html" ]

[functions.guestbook-update]
enabled = true
verify_jwt = true
import_map = "./functions/guestbook-update/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/guestbook-update/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/guestbook-update/*.html" ]
